# Generated by Django 6.0.3 on 2026-04-01 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('key', models.SlugField(help_text='Internal key for attribute', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('select', 'Select')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.attribute')),
            ],
            options={
                'ordering': ['order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g. FontAwesome or Material Icon)', max_length=50)),
                ('vertical', models.CharField(choices=[('property', 'Real Estate'), ('vehicle', 'Vehicles'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('is_service', models.BooleanField(default=False, help_text='Is this a service category?')),
                ('is_physical', models.BooleanField(default=True, help_text='Is this a physical product category?')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['vertical', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.category'),
        ),
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('key', models.SlugField()),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('boolean', 'Boolean'), ('date', 'Date')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, help_text='List of options for select fields (legacy)', null=True)),
                ('unit', models.CharField(blank=True, help_text='e.g. GB, square meters, Liters', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('field_name', models.SlugField(blank=True, help_text='Internal key (synced from key)')),
                ('field_label', models.CharField(blank=True, help_text='Human-readable label (synced from name)', max_length=100)),
                ('choices', models.JSONField(blank=True, help_text='List of choices for enum/multi_enum fields', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='catalog.category')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['vertical', 'is_active'], name='catalog_cat_vertica_7bc4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='catalog_cat_parent__e2d7e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('category', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryfield',
            unique_together={('category', 'key')},
        ),
    ]
