# Generated by Django 6.0.3 on 2026-04-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('long_text', 'Long Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('number', 'Number (Legacy)'), ('select', 'Select'), ('boolean', 'Boolean'), ('date', 'Date')], default='text', max_length=20),
        ),
    ]
