# Generated by Django 6.0.3 on 2026-04-01 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0002_initial'),
        ('communications', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='Listing context', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order context', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='commerce.order'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='communications.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['order', '-updated_at'], name='communicati_order_i_9f25a9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['listing', '-updated_at'], name='communicati_listing_3a5cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['dispute', '-updated_at'], name='communicati_dispute_923ad6_idx'),
        ),
    ]
