# Generated by Django 6.0.3 on 2026-04-01 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('suspend', 'Suspend'), ('reinstate', 'Reinstate'), ('business_approve', 'Business approve'), ('business_reject', 'Business reject')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='marketplace.sellerprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SellerBusinessVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_registration_no', models.CharField(blank=True, max_length=100)),
                ('tin_number', models.CharField(blank=True, max_length=50)),
                ('business_certificate', models.FileField(blank=True, null=True, upload_to='verifications/business/')),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_business_reviews', to=settings.AUTH_USER_MODEL)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_verification', to='marketplace.sellerprofile')),
            ],
            options={
                'verbose_name': 'Seller business verification',
            },
        ),
        migrations.CreateModel(
            name='SellerIDVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('voters_card', "Voter's card"), ('driving_license', 'Driving license')], max_length=30)),
                ('id_number', models.CharField(max_length=50)),
                ('id_front_image', models.ImageField(upload_to='verifications/id/')),
                ('selfie_with_id', models.ImageField(upload_to='verifications/selfies/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_id_reviews', to=settings.AUTH_USER_MODEL)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_verification', to='marketplace.sellerprofile')),
            ],
            options={
                'verbose_name': 'Seller ID verification',
                'verbose_name_plural': 'Seller ID verifications',
            },
        ),
        migrations.CreateModel(
            name='SellerOnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_registration', models.BooleanField(default=False)),
                ('step_store_setup', models.BooleanField(default=False)),
                ('step_id_submitted', models.BooleanField(default=False)),
                ('step_id_approved', models.BooleanField(default=False)),
                ('step_payout_added', models.BooleanField(default=False)),
                ('step_first_product', models.BooleanField(default=False)),
                ('step_business_upgraded', models.BooleanField(default=False)),
                ('upgrade_prompt_sent', models.BooleanField(default=False)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to='marketplace.sellerprofile')),
            ],
            options={
                'verbose_name': 'Seller onboarding progress',
            },
        ),
        migrations.CreateModel(
            name='SellerPayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('mpesa', 'M-Pesa'), ('tigo_pesa', 'Tigo Pesa'), ('airtel_money', 'Airtel Money'), ('bank', 'Bank')], max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to='marketplace.sellerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
