# Generated by Django 6.0.3 on 2026-04-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerpayoutaccount',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Selcom bank code (e.g. CRDB, NMB). Required for bank transfers.', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerpayoutaccount',
            name='account_type',
            field=models.CharField(choices=[('mpesa', 'M-Pesa (Vodacom)'), ('tigo_pesa', 'Tigo Pesa'), ('airtel_money', 'Airtel Money'), ('halopesa', 'HaloPesa'), ('ezypesa', 'EzyPesa'), ('azampesa', 'AzamPesa'), ('bank', 'Bank Transfer (Selcom Bridge)'), ('card_visa', 'Visa Card'), ('card_mastercard', 'Mastercard'), ('card_unionpay', 'UnionPay'), ('till', 'Selcom Till / TanQR')], default='mpesa', max_length=20),
        ),
    ]
