# Generated by Django 5.1.14 on 2026-04-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_sellerpayoutaccount_bank_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayoutaccount',
            name='account_type',
            field=models.CharField(choices=[('mpesa', 'M-PESA (Vodacom)'), ('tigo_pesa', 'Tigo Pesa'), ('airtel_money', 'Airtel Money'), ('halopesa', 'HaloPesa'), ('ezypesa', 'EzyPesa'), ('azampesa', 'AzamPesa'), ('bank', 'Bank Transfer'), ('card_visa', 'Visa'), ('card_mastercard', 'Mastercard'), ('card_unionpay', 'UnionPay'), ('till', 'Selcom Till / TanQR')], default='mpesa', max_length=20),
        ),
    ]
