# Generated by Django 6.0.4 on 2026-04-14 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_migrate_verification_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleridverification',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='selleridverification',
            name='seller',
        ),
        migrations.DeleteModel(
            name='SellerBusinessVerification',
        ),
        migrations.DeleteModel(
            name='SellerIDVerification',
        ),
    ]
