# Generated by Django 6.0.3 on 2026-04-01 11:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('listings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing_id', models.PositiveIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReputationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(default=0.0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Review comment')),
                ('seller_reply', models.TextField(blank=True, help_text="Seller's reply to this review", null=True)),
                ('is_flagged', models.BooleanField(default=False, help_text='Review flagged for moderation')),
                ('is_hidden', models.BooleanField(default=False, help_text='Review hidden from public view')),
                ('is_approved', models.BooleanField(default=True, help_text='Review approved by admin')),
                ('buyer', models.ForeignKey(help_text='Buyer writing the review', on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, help_text='Listing from order (auto-set from order items)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='listings.listing')),
                ('order', models.OneToOneField(help_text='Order this review is for (required, one review per order)', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='commerce.order')),
                ('seller', models.ForeignKey(help_text='Seller being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('listing', 'Listing'), ('user', 'User'), ('review', 'Review'), ('message', 'Message')], max_length=20)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('fraud', 'Fraud'), ('inappropriate', 'Inappropriate Content'), ('misleading', 'Misleading Information'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(blank=True, help_text='User this report is about; used for triage and automated suspension.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_report_subjects', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='trust.review')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('warn', 'Warning'), ('suspend', 'Suspend'), ('ban', 'Ban'), ('verify', 'Verify'), ('unverify', 'Unverify'), ('delete', 'Delete')], max_length=20)),
                ('target_type', models.CharField(choices=[('listing', 'Listing'), ('user', 'User'), ('review', 'Review')], max_length=20)),
                ('reason', models.TextField()),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Duration for temporary actions (suspend)', null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='listings.listing')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions_against', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='trust.review')),
            ],
            options={
                'verbose_name': 'Moderation Action',
                'verbose_name_plural': 'Moderation Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='reviews/media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='trust.review')),
            ],
            options={
                'verbose_name': 'Review Media',
                'verbose_name_plural': 'Review Media Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=50, help_text='Trust score from 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('id_verified', models.BooleanField(default=False)),
                ('tin_verified', models.BooleanField(default=False)),
                ('license_verified', models.BooleanField(default=False)),
                ('verification_status', models.BooleanField(default=False)),
                ('review_rating_avg', models.FloatField(default=0.0)),
                ('transaction_success_rate', models.FloatField(default=0.0)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('account_age_days', models.PositiveIntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trust Score',
                'verbose_name_plural': 'Trust Scores',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('national_id_front', models.FileField(blank=True, null=True, upload_to='verifications/id/')),
                ('national_id_back', models.FileField(blank=True, null=True, upload_to='verifications/id/')),
                ('id_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('tin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tin_certificate', models.FileField(blank=True, null=True, upload_to='verifications/tin/')),
                ('tin_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('business_license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('business_license_document', models.FileField(blank=True, null=True, upload_to='verifications/license/')),
                ('business_license_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('is_identity_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anomaly_type', models.CharField(choices=[('too_low', 'Suspiciously Low Price'), ('too_high', 'Suspiciously High Price'), ('price_drop', 'Sudden Price Drop'), ('price_spike', 'Sudden Price Spike'), ('category_mismatch', 'Price Mismatch with Category')], db_index=True, max_length=50)),
                ('score', models.FloatField(help_text='Anomaly score (0-1, higher = more suspicious)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('expected_price_range', models.JSONField(blank=True, default=dict, help_text='Expected price range based on similar listings')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deviation_percentage', models.FloatField(help_text='Percentage deviation from expected price')),
                ('is_reviewed', models.BooleanField(db_index=True, default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_anomalies', to='listings.listing')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_anomalies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Price Anomaly',
                'verbose_name_plural': 'Price Anomalies',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['is_reviewed', '-score'], name='trust_price_is_revi_32ae25_idx'), models.Index(fields=['anomaly_type', '-created_at'], name='trust_price_anomaly_ea7161_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['seller', '-created_at'], name='trust_revie_seller__030d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['buyer', '-created_at'], name='trust_revie_buyer_i_318f98_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order', '-created_at'], name='trust_revie_order_i_8992ed_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', '-created_at'], name='trust_revie_rating_1ec93f_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_hidden', 'is_approved'], name='trust_revie_is_hidd_cc5aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='trust_repor_status_1d8bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'status'], name='trust_repor_report__ecc843_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['subject_user', 'status', '-created_at'], name='trust_repor_subject_stat_c_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['target_type', 'is_active'], name='trust_moder_target__b39231_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['moderator', '-created_at'], name='trust_moder_moderat_5656bc_idx'),
        ),
    ]
