# Generated by Django 6.0.4 on 2026-04-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('voters_card', "Voter's card"), ('driving_license', 'Driving license')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='is_business_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userverification',
            name='selfie_with_id',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/selfies/'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='business_license_document',
            field=models.FileField(blank=True, null=True, upload_to='verifications/id/'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='tin_certificate',
            field=models.FileField(blank=True, null=True, upload_to='verifications/id/'),
        ),
    ]
