# Generated by Django 6.0.3 on 2026-04-01 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('evidence_video', models.FileField(blank=True, null=True, upload_to='engine/disputes/videos/')),
                ('evidence_images_count', models.PositiveIntegerField(default=0)),
                ('resolution', models.TextField(blank=True)),
                ('resolution_type', models.CharField(blank=True, choices=[('refund_buyer', 'Refund to Buyer'), ('release_seller', 'Release to Seller'), ('partial_refund', 'Partial Refund'), ('no_action', 'No Action Required')], max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_order', models.OneToOneField(blank=True, help_text='Set when dispute originated from a marketplace order. Use transaction as primary reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engine_dispute', to='commerce.order')),
                ('opened_by', models.ForeignKey(blank=True, help_text='Null for system-generated disputes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engine_disputes_opened', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engine_disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='engine/dispute_evidence/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='escrow_engine.dispute')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_dispute_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute Evidence',
                'verbose_name_plural': 'Dispute Evidence Items',
            },
        ),
        migrations.CreateModel(
            name='PayoutDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa (Vodacom)'), ('tigo_pesa', 'Tigo Pesa'), ('airtel_money', 'Airtel Money'), ('halopesa', 'HaloPesa'), ('ezypesa', 'EzyPesa'), ('azampesa', 'AzamPesa'), ('bank', 'Bank Transfer (Selcom Bridge)'), ('card_visa', 'Visa Card'), ('card_mastercard', 'Mastercard'), ('card_unionpay', 'UnionPay'), ('till', 'Selcom Till / TanQR')], default='mpesa', help_text='Payment channel via Selcom aggregator.', max_length=20)),
                ('account_number', models.CharField(help_text='Phone number for mobile money; account number for bank; till number for Till/QR.', max_length=50)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('bank_code', models.CharField(blank=True, help_text='Selcom bank code (e.g. CRDB, NMB, EQUITY). Required for bank transfers.', max_length=20)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout Destination',
                'verbose_name_plural': 'Payout Destinations',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('HOLD', 'Hold'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='CREATED', max_length=20)),
                ('source', models.CharField(choices=[('marketplace', 'Marketplace'), ('external', 'External (WhatsApp / Off-Platform)'), ('api', 'Third-Party API')], db_index=True, default='marketplace', max_length=20)),
                ('buyer_phone', models.CharField(blank=True, max_length=30)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('seller_phone', models.CharField(blank=True, max_length=30)),
                ('seller_email', models.EmailField(blank=True, max_length=254)),
                ('external_reference', models.CharField(blank=True, db_index=True, help_text="Reference from developer API caller's system.", max_length=255)),
                ('payment_method', models.CharField(blank=True, help_text='mpesa, selcom, stripe, bank_transfer, etc.', max_length=50)),
                ('gateway_reference', models.CharField(blank=True, help_text='Transaction ID returned by the payment gateway.', max_length=255)),
                ('gateway_payload', models.JSONField(blank=True, help_text='Raw response from payment gateway for debugging.', null=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary key/value data from source system.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('auto_release_at', models.DateTimeField(blank=True, help_text='When funds will be automatically released to the seller if no dispute is raised.', null=True)),
                ('preferred_provider', models.CharField(blank=True, help_text='Explicitly override the payment provider for this transaction.', max_length=50)),
                ('buyer_user', models.ForeignKey(blank=True, help_text='Registered buyer. Null for external/anonymous flows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_buyer_transactions', to=settings.AUTH_USER_MODEL)),
                ('dispute_resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('linked_order', models.OneToOneField(blank=True, help_text='Set when this transaction originates from a marketplace order. Null for external/API transactions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engine_transaction', to='commerce.order')),
                ('seller_user', models.ForeignKey(blank=True, help_text='Registered seller. Null for external flows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_seller_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('payout_method', models.CharField(default='mpesa', help_text='Selcom channel used for payout: mpesa, tigo_pesa, airtel_money, halopesa, ezypesa, azampesa, bank, card_visa, card_mastercard, card_unionpay, till.', max_length=50)),
                ('payout_reference', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_payouts', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='escrow_engine.transaction')),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='selcom', help_text='mpesa, selcom, stripe, bank_transfer, etc.', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Transaction ID returned by the payment gateway.', max_length=255)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='commerce.order')),
                ('transaction', models.ForeignKey(blank=True, help_text='Engine transaction this record belongs to. Null for legacy records attached via order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='escrow_engine.transaction')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('otp_code', models.CharField(blank=True, max_length=8)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('buyer_phone_verified', models.CharField(blank=True, help_text='Phone used during OTP verification — becomes the buyer identity.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_links', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='escrow_engine.transaction')),
            ],
            options={
                'verbose_name': 'Payment Link',
                'verbose_name_plural': 'Payment Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dispute',
            name='transaction',
            field=models.OneToOneField(help_text='Transaction this dispute is against.', on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='escrow_engine.transaction'),
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('actor_label', models.CharField(blank=True, help_text="System label for the actor (e.g. 'System', 'Celery: auto-release', 'Buyer').", max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, help_text='User who triggered the transition. Null for system/async actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='escrow_engine.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='escrow_engi_status_ddbe32_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['source', 'status'], name='escrow_engi_source_459106_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer_user', '-created_at'], name='escrow_engi_buyer_u_857cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['seller_user', '-created_at'], name='escrow_engi_seller__e8d755_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['gateway_reference'], name='escrow_engi_gateway_0b7f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['reference'], name='escrow_engi_referen_416560_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['status', '-created_at'], name='escrow_engi_status_9e93e3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['token', 'is_used'], name='escrow_engi_token_604206_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['expires_at'], name='escrow_engi_expires_f44cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', '-created_at'], name='escrow_engi_status_1e609a_idx'),
        ),
    ]
