# Generated by Django 6.0.3 on 2026-04-04 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escrow_engine', '0004_gateway_event_apikey_hardening'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gatewayevent',
            new_name='escrow_engi_provide_a0a9ec_idx',
            old_name='escrow_gate_provide_2f5c8e_idx',
        ),
    ]
