# Generated by Django 5.1.14 on 2026-04-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow_engine', '0005_rename_escrow_gate_provide_2f5c8e_idx_escrow_engi_provide_a0a9ec_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutdestination',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-PESA (Vodacom)'), ('tigo_pesa', 'Tigo Pesa'), ('airtel_money', 'Airtel Money'), ('halopesa', 'HaloPesa'), ('ezypesa', 'EzyPesa'), ('azampesa', 'AzamPesa'), ('bank', 'Bank Transfer'), ('card_visa', 'Visa'), ('card_mastercard', 'Mastercard'), ('card_unionpay', 'UnionPay'), ('till', 'Selcom Till / TanQR')], default='mpesa', help_text='Payment channel via Selcom aggregator.', max_length=20),
        ),
    ]
