"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import sentry_sdk
import warnings
# Suppress "StreamingHttpResponse must consume synchronous iterators" warning 
# which occurs when using WhiteNoise with ASGI
warnings.filterwarnings("ignore", message="StreamingHttpResponse must consume synchronous iterators")
import dj_database_url
from datetime import timedelta
from decimal import Decimal
from sentry_sdk.integrations.django import DjangoIntegration
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv()  # take environment variables from .env.


def _env_float(name: str, default: float = 0.0) -> float:
    raw = os.getenv(name)
    if raw is None or str(raw).strip() == '':
        return default
    return float(raw)


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None or str(raw).strip() == '':
        return default
    return str(raw).lower() in ('1', 'true', 'yes')


# Observability / Error tracking
SENTRY_DSN = os.getenv('SENTRY_DSN')
if SENTRY_DSN:
    def sentry_before_send(event, hint):
        """Scrub PII from Sentry before event is sent."""
        sensitive_keys = {'password', 'account_number', 'msisdn', 'phone', 'token'}
        
        # Scrub request data
        request = event.get('request', {})
        if 'data' in request:
            if isinstance(request['data'], dict):
                for k in request['data']:
                    if k.lower() in sensitive_keys:
                        request['data'][k] = '***REDACTED***'
        
        # Scrub extra context
        extra = event.get('extra', {})
        if isinstance(extra, dict):
            for k in extra:
                if k.lower() in sensitive_keys:
                    extra[k] = '***REDACTED***'
        
        return event

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=_env_float('SENTRY_TRACES_SAMPLE_RATE', 0.0),
        profiles_sample_rate=_env_float('SENTRY_PROFILES_SAMPLE_RATE', 0.0),
        send_default_pii=_env_bool('SENTRY_SEND_DEFAULT_PII', False),
        before_send=sentry_before_send,
    )
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read SECRET_KEY from environment; REQUIRED in production, fallback only for development.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if os.getenv('DJANGO_ENV') == 'production':
        raise ValueError(
            "SECRET_KEY environment variable is required in production. "
            "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
        )
    from django.core.management.utils import get_random_secret_key

    SECRET_KEY = get_random_secret_key()

# DEBUG should be False in production. Control via environment variable.
# Fallback to False for safety; explicitly set to True in local .env for development.
DEBUG = os.getenv('DEBUG', 'false').lower() in ('1', 'true', 'yes')


def show_debug_toolbar(request):
    """Keep DebugToolbarMiddleware in MIDDLEWARE always (W001); only inject toolbar when DEBUG."""
    from django.conf import settings as dj_settings

    return dj_settings.DEBUG

# Allowed hosts configuration
_ALLOWED_HOSTS_ENV = os.getenv('ALLOWED_HOSTS', '').strip()

if _ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [h.strip() for h in _ALLOWED_HOSTS_ENV.split(',') if h.strip()]
elif DEBUG:
    # Development defaults
    ALLOWED_HOSTS = ['*']
else:
    # Production safety: requires explicit ALLOWED_HOSTS env var
    ALLOWED_HOSTS = []

# Validate production settings
if not DEBUG or os.getenv('DJANGO_ENV') == 'production':
    if not ALLOWED_HOSTS or '*' in ALLOWED_HOSTS:
        # In production/deployment, we MUST have a restricted list of hosts
        if os.getenv('DJANGO_ENV') == 'production':
             raise ValueError("ALLOWED_HOSTS must be explicitly set in production and not contain '*'.")
        
    if not os.getenv('CSRF_TRUSTED_ORIGINS'):
        if os.getenv('DJANGO_ENV') == 'production':
            raise ValueError("CSRF_TRUSTED_ORIGINS must be explicitly set in production.")
    
    if not os.getenv('CORS_ALLOWED_ORIGINS'):
        if os.getenv('DJANGO_ENV') == 'production':
            raise ValueError("CORS_ALLOWED_ORIGINS must be explicitly set in production.")

# Security-sensitive settings that should be set for production.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Additional security headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CROSS_ORIGIN_OPENER_POLICY ='same-origin-allow-popups'
SECURE_CROSS_ORIGIN_EMBEDDER_POLICY ='unsafe-none'
X_FRAME_OPTIONS = 'DENY'

# HTTPS / HSTS / proxy: single block (avoids duplicate SECURE_* assignments)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'true').lower() in ('true', '1', 'yes')
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'true').lower() in (
        'true',
        '1',
        'yes',
    )
    SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'true').lower() in ('true', '1', 'yes')
else:
    SECURE_PROXY_SSL_HEADER = None
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Cookie settings - adjusted for cross-origin requests
# In development: Use 'Lax' for SameSite (works with Secure=False)
# In production: Use 'None' with Secure=True for cross-site cookies
if DEBUG:
    # Development: Use Lax to allow cookies to work without Secure flag
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
else:
    # Production: Use None with Secure=True for cross-site cookies
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False  # Must be False for frontend to read CSRF token
CSRF_USE_SESSIONS = False
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = False


# Application definition
# debug_toolbar: always in INSTALLED_APPS so models (e.g. HistoryEntry) and migrations stay consistent
# when other apps (e.g. cachalot with ENABLE_CACHALOT) or tooling import the package. Middleware and
# URLs are DEBUG-only — no toolbar runs in production.
# Silk: DEBUG only (heavier DB surface). Cachalot: DEBUG or ENABLE_CACHALOT=1 (explicit prod opt-in).
ENABLE_CACHALOT = os.getenv('ENABLE_CACHALOT', '').lower() in ('1', 'true', 'yes')
ENABLE_SILK = os.getenv('ENABLE_SILK', '').lower() in ('1', 'true', 'yes')

INSTALLED_APPS = [
    'daphne',
    'corsheaders',
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.postgres',
    'django_filters',
    'parler',  # Django-parler for model translations
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.apple',
    'allauth.socialaccount.providers.microsoft',
    'anymail',
    'cloudinary',
    'cloudinary_storage',
    'storages',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework.authtoken', # Added as per instruction
    'drf_spectacular',
    'channels',

    # Local apps
    'core', # Added as per instruction
    'accounts',
    'communications',
    'insights',
    'features',
    'shortlinks',
    'marketplace',
    'sellers',
    'listings',
    'catalog',
    'media_app',
    'commerce',  # Marketplace commerce (orders, cart, delivery — financial state in escrow_engine)
    'trust',
    'search',
    'analytics',
    'escrow_engine',
    'django_celery_beat',
    'django_celery_results',

    # Security
    'axes',
    'debug_toolbar',
]

if ENABLE_CACHALOT and not ENABLE_SILK:
    INSTALLED_APPS.append('cachalot')

if ENABLE_SILK:
    INSTALLED_APPS.append('silk')

SITE_ID = 1

# Django-allauth configuration
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = os.getenv('ACCOUNT_EMAIL_VERIFICATION', 'mandatory')
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_VERIFICATION = os.getenv('SOCIALACCOUNT_EMAIL_VERIFICATION', 'optional')
ACCOUNT_EMAIL_REQUIRED = True
# Redirect after login (you can change this to your frontend URL)
LOGIN_REDIRECT_URL = os.getenv('LOGIN_REDIRECT_URL', '/')

# Social provider placeholders.
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.getenv('SOCIAL_GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('SOCIAL_GOOGLE_SECRET', ''),
            'key': ''
        }
    },
    'facebook': {
        'SCOPE': ['email'],
        'APP': {
            'client_id': os.getenv('SOCIAL_FACEBOOK_CLIENT_ID', ''),
            'secret': os.getenv('SOCIAL_FACEBOOK_SECRET', ''),
            'key': ''
        }
    },
    'microsoft': {
        'SCOPE': ['User.Read'],
        'APP': {
            'client_id': os.getenv('SOCIAL_MICROSOFT_CLIENT_ID', ''),
            'secret': os.getenv('SOCIAL_MICROSOFT_SECRET', ''),
            'key': ''
        }
    },
    'apple': {
        'APP': {
            'client_id': os.getenv('SOCIAL_APPLE_CLIENT_ID', ''),
            'secret': os.getenv('SOCIAL_APPLE_SECRET', ''),
            'key': ''
        }
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'PAGE_SIZE_QUERY_PARAM': 'limit',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ] if not DEBUG else [],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20000/hour' if DEBUG else '100/day',
        'user': '50000/hour' if DEBUG else '1000/day',
        # Auth: scoped throttles for login/refresh (IP-based)
        'auth_login': '2000/hour' if DEBUG else '20/hour',
        'auth_refresh': '6000/hour' if DEBUG else '60/hour',
        'listing_list_anon': '300/min',
        'listing_list_user': '600/min',
        'messages': '60/min',  # Messaging-specific rate limit
        'conversations': '20/hour',  # Conversation creation rate limit
        'listings': '1000/hour',  # Specific rate for listing reads
        # Escrow payment links: per (link token, IP); see escrow_engine.throttling.EscrowPaymentLinkScopedThrottle
        'escrow_payment_link': '200/hour' if DEBUG else '40/hour',
        'commerce_checkout': '60/min' if DEBUG else '10/min',
        'commerce_payment_initiate': '30/min' if DEBUG else '8/min',
        'commerce_payment_return': '30/min' if DEBUG else '8/min',
        'commerce_dispute': '20/min' if DEBUG else '5/min',
        # Shortlinks: public endpoint, keep tight in production
        'shortlinks_create': '60/hour' if DEBUG else '10/hour',
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] if not DEBUG else [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.FirebaseAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'backend.api_exception_handler.custom_exception_handler',
}

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# CSRF trusted origins - MUST be set in production
csrf_origins_env = os.getenv('CSRF_TRUSTED_ORIGINS')
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(',') if origin.strip()]
elif not DEBUG:
    CSRF_TRUSTED_ORIGINS = [] # Empty list is a safe default if not debug
else:
    # Default development origins if not set
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:3000', 'http://127.0.0.1:3000',  # Frontend
        'http://localhost:3001', 'http://127.0.0.1:3001',  # Dashboards
        'http://localhost:8000', 'http://127.0.0.1:8000',  # Admin / API same origin
    ]

# CORS allowed origins - MUST be set in production
cors_origins_env = os.environ.get('CORS_ALLOWED_ORIGINS')
if cors_origins_env:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(',') if origin.strip()]
elif not DEBUG:
    CORS_ALLOWED_ORIGINS = [] # Empty list is a safe default if not debug
else:
    # Default development origins
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000', 'http://127.0.0.1:3000',  # Frontend
        'http://localhost:3001', 'http://127.0.0.1:3001',  # Dashboards
        'http://localhost:5173', 'http://127.0.0.1:5173',  # Vite dev server
        'http://localhost:8000', 'http://127.0.0.1:8000',  # Backend
    ]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ('DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT')
CORS_ALLOW_HEADERS = (
    'accept',
    'authorization',
    'content-type',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'sec-websocket-protocol',   # WebSocket support
    'sec-websocket-extensions',  # WebSocket support
)
CORS_ALLOW_ALL_ORIGINS = False  # Explicitly set for security

GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY')
GOOGLE_MAPS_GEOCODE_TIMEOUT = int(os.getenv('GOOGLE_MAPS_GEOCODE_TIMEOUT', 5))
REDIS_URL = os.getenv('REDIS_URL')

# Message Encryption Configuration
# Generate key with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
from cryptography.fernet import Fernet
MESSAGE_ENCRYPTION_KEY = os.getenv('MESSAGE_ENCRYPTION_KEY')
if not MESSAGE_ENCRYPTION_KEY:
    if os.getenv('DJANGO_ENV') == 'production':
        raise ValueError("MESSAGE_ENCRYPTION_KEY must be set in production environment")
    else:
        # Generate temporary key for development
        MESSAGE_ENCRYPTION_KEY = Fernet.generate_key().decode()
        import logging
        logger = logging.getLogger(__name__)
        logger.warning("Using temporary encryption key. Set MESSAGE_ENCRYPTION_KEY in .env for persistence.")


# M-Pesa Payment Integration (Daraja API)
DAR_AFFILIATE_CONSUMER_KEY = os.getenv('DAR_AFFILIATE_CONSUMER_KEY')
DAR_AFFILIATE_CONSUMER_SECRET = os.getenv('DAR_AFFILIATE_CONSUMER_SECRET')
DAR_SHORTCODE = os.getenv('DAR_SHORTCODE')
DAR_PASSKEY = os.getenv('DAR_PASSKEY')
MPESA_API_BASE = os.getenv('MPESA_API_BASE', 'https://sandbox.safaricom.co.ke')
MPESA_CALLBACK_URL = os.getenv('MPESA_CALLBACK_URL')

# Twilio SMS Integration
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER')

# Stripe Payment Integration
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')

# Marketplace commission default percent (fallback when env unset; SiteConfiguration used in checkout rules too)
_MARKETPLACE_DEFAULT_COMMISSION_RAW = os.getenv('MARKETPLACE_DEFAULT_COMMISSION')
MARKETPLACE_DEFAULT_COMMISSION = (
    float(_MARKETPLACE_DEFAULT_COMMISSION_RAW)
    if _MARKETPLACE_DEFAULT_COMMISSION_RAW not in (None, '')
    else 5.0
)

# Payment Gateway Configuration
PAYMENT_GATEWAYS = {
    'mpesa': {
        'enabled': os.getenv('MPESA_ENABLED', 'True').lower() in ('true', '1', 'yes'),
        'api_key': DAR_AFFILIATE_CONSUMER_KEY,
        'api_secret': DAR_AFFILIATE_CONSUMER_SECRET,
        'shortcode': DAR_SHORTCODE,
        'passkey': DAR_PASSKEY,
        'base_url': MPESA_API_BASE,
        'callback_url': MPESA_CALLBACK_URL,
        'environment': os.getenv('MPESA_ENVIRONMENT', 'sandbox'),  # sandbox or production
    },
    'stripe': {
        'enabled': os.getenv('STRIPE_ENABLED', 'False').lower() in ('true', '1', 'yes'),
        'publishable_key': STRIPE_PUBLISHABLE_KEY,
        'secret_key': STRIPE_SECRET_KEY,
        'webhook_secret': STRIPE_WEBHOOK_SECRET,
        'currency': os.getenv('STRIPE_CURRENCY', 'TZS'),
    },
}

# Dashboard Polling Configuration (in milliseconds)
DASHBOARD_POLLING_INTERVAL = int(os.getenv('DASHBOARD_POLLING_INTERVAL', '30000'))  # 30 seconds default
ADMIN_DASHBOARD_POLLING_INTERVAL = int(os.getenv('ADMIN_DASHBOARD_POLLING_INTERVAL', '30000'))
SELLER_DASHBOARD_POLLING_INTERVAL = int(os.getenv('SELLER_DASHBOARD_POLLING_INTERVAL', '30000'))
BUYER_DASHBOARD_POLLING_INTERVAL = int(os.getenv('BUYER_DASHBOARD_POLLING_INTERVAL', '30000'))

# Frontend URL used in activation emails and links
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# Marketplace: require admin-approved identity before items become public (progressive onboarding).
# Set MARKETPLACE_PUBLISH_REQUIRES_IDENTITY_VERIFICATION=false for local/demo without verification flows.
MARKETPLACE_PUBLISH_REQUIRES_IDENTITY_VERIFICATION = os.getenv(
    'MARKETPLACE_PUBLISH_REQUIRES_IDENTITY_VERIFICATION',
    'true',
).lower() in ('1', 'true', 'yes')

_CORE_MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Top priority for pre-flight handling
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.CorrelationIdMiddleware',
    'escrow_engine.middleware.EscrowSecurityHeadersMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'insights.middleware.VisitorTrackingMiddleware',
    'axes.middleware.AxesMiddleware',
]

# debug_toolbar middleware must stay listed whenever the app is installed (system check W001).
# Visibility is gated by DEBUG via DEBUG_TOOLBAR_CONFIG['SHOW_TOOLBAR_CALLBACK'].
_DEBUG_TOOLBAR_MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

_SILK_MIDDLEWARE = [
    'silk.middleware.SilkyMiddleware',
]

MIDDLEWARE = (
    _DEBUG_TOOLBAR_MIDDLEWARE
    + (_SILK_MIDDLEWARE if ENABLE_SILK else [])
    + _CORE_MIDDLEWARE
)

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'


# Database
# Use PostgreSQL in production. Use dj-database-url to parse DATABASE_URL env var.

# Check if running on Render (which uses ephemeral storage) to enforce PostgreSQL
IS_RENDER = os.getenv('RENDER')

if os.getenv('DJANGO_ENV') == 'production' or IS_RENDER:
    # On Render, we must use PostgreSQL to avoid data loss (ephemeral filesystem)
    print("🚀 Using Production/Render Settings: PostgreSQL Database")
    _db = dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=True,
    )
    _engine = _db.get('ENGINE', '')
    if 'postgresql' in _engine:
        _opts = dict(_db.get('OPTIONS') or {})
        _opts.setdefault('connect_timeout', 5)
        _pgopts = _opts.get('options', '') or ''
        if 'statement_timeout' not in _pgopts:
            _pgopts = f"{_pgopts} -c statement_timeout=30000".strip()
            _opts['options'] = _pgopts
        _db['OPTIONS'] = _opts
    DATABASES = {'default': _db}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                # Wait up to 20s for the write lock to clear before raising
                # OperationalError: database is locked. Eliminates spurious
                # lock errors when Django admin, Celery beat, and API requests
                # all hit the single SQLite file concurrently in development.
                'timeout': 20,
            },
        }
    }


# Cache configuration
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': False,  # Strict mode for production
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 25,
                    'retry_on_timeout': True,
                },
            },
            'KEY_PREFIX': 'smartdalali_prod',
        }
    }
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'property-cache',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 9}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# JWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    # "AUDIENCE": os.getenv("JWT_AUDIENCE", "smartdalali:web"),
    # "ISSUER": os.getenv("JWT_ISSUER", "smartdalali"),
    "LEEWAY": int(os.getenv("JWT_LEEWAY_SECONDS", 5)),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_OBTAIN_SERIALIZER": "accounts.serializers.MyTokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "accounts.serializers.MyTokenRefreshSerializer",
}

# Channels
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'}}


# Internationalization
LANGUAGE_CODE = 'en'
LANGUAGES = [('en', 'English'), ('sw', 'Kiswahili')]
LOCALE_PATHS = [BASE_DIR / 'locale']
TIME_ZONE = 'Africa/Dar_es_Salaam'
USE_I18N = True
USE_TZ = True

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/1')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_RESULT_EXTENDED = True

# Route Selcom (gateway) webhook processing to a dedicated queue so long-running default tasks
# cannot starve payment events (Render: run a worker with `-Q escrow_webhooks`).
CELERY_TASK_ROUTES = {
    'escrow_engine.tasks.process_gateway_webhook_event': {'queue': 'escrow_webhooks'},
}

# Escrow engine: async webhooks in production by default (requires workers consuming escrow_webhooks).
# Override with ESCROW_WEBHOOK_ASYNC=false if you must process synchronously (not recommended).
ESCROW_WEBHOOK_ASYNC = os.getenv(
    'ESCROW_WEBHOOK_ASYNC',
    'true' if os.getenv('DJANGO_ENV') == 'production' else 'false',
).lower() in ('1', 'true', 'yes')
# Production: never set. When True with DEBUG, Selcom webhooks skip HMAC (local testing only).
ESCROW_WEBHOOK_INSECURE_SKIP_VERIFY = (
    DEBUG
    and os.getenv('ESCROW_WEBHOOK_INSECURE_SKIP_VERIFY', '').lower() in ('1', 'true', 'yes')
)
ESCROW_STUCK_PAYOUT_MINUTES = 30

# Dev-only: strict order ↔ escrow checks (serializer, retrieve, lifecycle). Default off for tests/CI.
ESCROW_PARANOID_MODE = os.getenv('ESCROW_PARANOID_MODE', '').lower() in ('1', 'true', 'yes')

# Reconciliation scan (commerce.services.reconciliation): lookback window and optional deterministic auto-fix.
RECONCILIATION_LOOKBACK_DAYS = int(os.getenv('RECONCILIATION_LOOKBACK_DAYS', '30'))
RECONCILIATION_AUTO_FIX = os.getenv('RECONCILIATION_AUTO_FIX', '').lower() in ('1', 'true', 'yes')
# When False, reconciliation only logs + emits events (no sync_order / release / payout creation).
# Default false: opt in explicitly in production when ops-approved.
RECONCILIATION_ALLOW_MUTATING_FIX = os.getenv('RECONCILIATION_ALLOW_MUTATING_FIX', 'false').lower() in (
    '1',
    'true',
    'yes',
)

# Checkout: delivery fee per `shipping_method` key (same currency as orders, typically TZS).
# Server is the source of truth — clients must not override `shipping_cost` at checkout.
COMMERCE_SHIPPING_RATES = {
    'standard': Decimal(os.getenv('COMMERCE_SHIPPING_STANDARD_FEE', '5000.00')),
    'express': Decimal(os.getenv('COMMERCE_SHIPPING_EXPRESS_FEE', '15000.00')),
    'pickup': Decimal(os.getenv('COMMERCE_SHIPPING_PICKUP_FEE', '0.00')),
}

# Outbox publisher (core.OutboxEvent → Celery)
OUTBOX_PUBLISH_BATCH_SIZE = int(os.getenv('OUTBOX_PUBLISH_BATCH_SIZE', '100'))
OUTBOX_PUBLISH_MAX_RETRIES = int(os.getenv('OUTBOX_PUBLISH_MAX_RETRIES', '10'))

# Celery Beat Schedule
from celery.schedules import crontab, schedule
CELERY_BEAT_SCHEDULE = {
    'check-unpaid-orders-hourly': {
        'task': 'commerce.tasks.check_unpaid_orders_periodic',
        'schedule': crontab(minute=0), # Every hour
    },
    'check-escrow-release-hourly': {
        'task': 'escrow_engine.tasks.release_delivered_marketplace_escrow_periodic',
        'schedule': crontab(minute=0), # Every hour
    },
    'cleanup-expired-reservations-ten-min': {
        'task': 'commerce.tasks.cleanup_expired_reservations_periodic',
        'schedule': crontab(minute='*/10'), # Every 10 minutes
    },
    'escrow-recover-stuck-payouts': {
        'task': 'escrow_engine.tasks.recover_stuck_payouts',
        'schedule': crontab(minute='*/15'),
    },
    # Auto-release HOLD when auto_release_at has passed (see escrow_engine.tasks.process_auto_releases)
    'escrow-process-auto-releases': {
        'task': 'escrow_engine.tasks.process_auto_releases',
        'schedule': crontab(minute='*/15'),
    },
    'reconcile-orders-escrow-daily': {
        'task': 'commerce.tasks.reconcile_orders_escrow_periodic',
        'schedule': crontab(hour=3, minute=15),
    },
    'publish-outbox-events': {
        'task': 'core.tasks.publish_outbox_events_periodic',
        'schedule': schedule(run_every=45.0),
    },
    'reconcile-orders-escrow-healing': {
        'task': 'commerce.tasks.reconciliation_healing_periodic',
        'schedule': schedule(run_every=300.0),
    },
    'escrow-auto-resolve-disputes': {
        'task': 'escrow_engine.tasks.auto_resolve_unresponsive_seller_disputes_periodic',
        'schedule': crontab(minute='*/30'), # Every 30 minutes
    },
}

# Django-parler configuration
PARLER_LANGUAGES = {
    None: (
        {'code': 'en'},
        {'code': 'sw'},
    ),
    'default': {
        'fallback': 'en',
        'hide_untranslated': False,
    }
}
PARLER_DEFAULT_LANGUAGE_CODE = 'en'

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static_root"
# In DEBUG, skip manifest storage + serve from app finders so admin/static work without
# collectstatic (docker-compose often runs runserver only and never runs build.sh).
if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
    WHITENOISE_USE_FINDERS = True
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads) - Cloudinary Configuration with Local Fallback
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME')
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET')

# Default Media Configuration (Local fallback or static reference)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

if CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
        'SECURE': True,
    }
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
    
    # Explicitly configure cloudinary SDK for direct usage if needed
    import cloudinary
    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=CLOUDINARY_API_KEY,
        api_secret=CLOUDINARY_API_SECRET,
        secure=True
    )
else:
    # Fallback to local storage if Cloudinary is not configured
    if os.getenv('DJANGO_ENV') == 'production':
         raise ValueError("Cloudinary MUST be configured in production! Local storage is ephemeral and will cause data loss.")
    
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    
    import logging
    logger = logging.getLogger(__name__)
    logger.info("Using local file storage for development.")

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'webmaster@localhost')

# Transactional email providers (e.g., SendGrid)
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
if SENDGRID_API_KEY:
    EMAIL_BACKEND = 'anymail.backends.sendgrid.EmailBackend'
    ANYMAIL = {'SENDGRID_API_KEY': SENDGRID_API_KEY}

LOGOUT_REDIRECT_URL = '/'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'verbose'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        'django': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}

# drf-spectacular (API Schema) settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'DigitalDalali API',
    'DESCRIPTION': 'API for property listings, user management, and more.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_PATCH': True,
    'ENUM_NAME_OVERRIDES': {
        # communications
        'MessageStatusEnum': 'communications.constants.MessageStatus',
        'SupportRequestStatusEnum': 'communications.constants.SupportRequestStatus',
        # features
        'FeatureStatusEnum': 'features.constants.FeatureStatus',
        # escrow engine
        'PaymentRecordStatusEnum': 'escrow_engine.models.payment_record.PaymentRecordStatus',
        'TransactionStatusEnum': 'escrow_engine.state_machine.TransactionStatus',
        'DisputeStatusEnum': 'escrow_engine.models.dispute.DisputeStatus',
        # sellers
        'SellerVerificationStatusEnum': 'sellers.constants.SellerVerificationStatus',
        # trust
        'UserVerificationStatusEnum': 'trust.constants.UserVerificationStatus',
        # core / listings
        'ListingStatusEnum': 'core.constants.ListingStatus',
        # commerce
        'OrderStatusEnum': 'commerce.constants.OrderStatus',
        'DeliveryStatusEnum': 'commerce.constants.DeliveryStatus',
        'StockReservationStatusEnum': 'commerce.constants.StockReservationStatus',
        # marketplace
        'StoreCategoryEnum': 'marketplace.constants.StoreCategory',
        'VerificationStatusEnum': 'marketplace.constants.VerificationStatus',
    },
    'DISABLE_ERRORS_AND_WARNINGS': False,
}

# Firebase Admin SDK Configuration
FIREBASE_CREDENTIALS_JSON = os.getenv('FIREBASE_CREDENTIALS_JSON')

# AI Configuration
AI_API_KEY = os.getenv('AI_API_KEY')

# Typesense Search
TYPESENSE_HOST = os.getenv('TYPESENSE_HOST', 'localhost')
TYPESENSE_PORT = os.getenv('TYPESENSE_PORT', '8108')
TYPESENSE_PROTOCOL = os.getenv('TYPESENSE_PROTOCOL', 'http')
TYPESENSE_API_KEY = os.getenv('TYPESENSE_API_KEY')
TYPESENSE_COLLECTION = os.getenv('TYPESENSE_COLLECTION', 'products')

# Google Vision
GOOGLE_VISION_PROJECT_ID = os.getenv('GOOGLE_VISION_PROJECT_ID')
GOOGLE_VISION_PRIVATE_KEY_ID = os.getenv('GOOGLE_VISION_PRIVATE_KEY_ID')
GOOGLE_VISION_PRIVATE_KEY = os.getenv('GOOGLE_VISION_PRIVATE_KEY')
GOOGLE_VISION_CLIENT_EMAIL = os.getenv('GOOGLE_VISION_CLIENT_EMAIL')
GOOGLE_VISION_CLIENT_ID = os.getenv('GOOGLE_VISION_CLIENT_ID')
GOOGLE_VISION_CLIENT_CERT_URL = os.getenv('GOOGLE_VISION_CLIENT_CERT_URL')

# Order Configuration
# Number of days after which an arrived order is automatically marked as delivered
AUTO_CONFIRM_RECEIPT_DAYS = int(os.getenv('AUTO_CONFIRM_RECEIPT_DAYS', '7'))

# Escrow Engine
# OTP lifetime for payment-link phone verification (minutes)
PAYMENT_LINK_OTP_MINUTES = int(os.getenv('PAYMENT_LINK_OTP_MINUTES', '10'))
# Backend URL used by payment providers for webhook URLs
BACKEND_URL = os.getenv('BACKEND_URL', 'http://localhost:8000')

# Trust / abuse reports — distinct reporters with open reports in the lookback window
TRUST_REPORT_AUTO_SUSPEND_THRESHOLD = int(os.getenv('TRUST_REPORT_AUTO_SUSPEND_THRESHOLD', '5'))
TRUST_REPORT_LOOKBACK_DAYS = int(os.getenv('TRUST_REPORT_LOOKBACK_DAYS', '90'))
TRUST_REPORT_MIN_DESCRIPTION_LEN = int(os.getenv('TRUST_REPORT_MIN_DESCRIPTION_LEN', '10'))
TRUST_REPORT_MAX_DESCRIPTION_LEN = int(os.getenv('TRUST_REPORT_MAX_DESCRIPTION_LEN', '5000'))

# axes settings
AXES_ENABLED = True
AXES_FAILURE_LIMIT = int(os.getenv('AXES_FAILURE_LIMIT', '5'))
AXES_COOLOFF_TIME = int(os.getenv('AXES_COOLOFF_TIME', '1')) # 1 hour
AXES_LOCKOUT_TEMPLATE = None # Can set custom template later
# Trust X-Forwarded-For only when behind a real proxy (e.g. Render). Local runserver: use 0.
AXES_IPWARE_PROXY_COUNT = int(os.getenv('AXES_IPWARE_PROXY_COUNT', '0' if DEBUG else '1'))
AXES_IPWARE_META_PRECEDENCE_ORDER = [
   'HTTP_X_FORWARDED_FOR',
   'REMOTE_ADDR',
]
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
AXES_RESET_ON_SUCCESS = True
AXES_ENABLE_ADMIN = True

# debug_toolbar settings
INTERNAL_IPS = [
    "127.0.0.1",
]

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': 'backend.settings.show_debug_toolbar',
}

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.history.HistoryPanel',
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
]

# silk settings
# NOTE: Keep Python profiler disabled by default to avoid
# "Another profiling tool is already active" runtime errors.
SILKY_PYTHON_PROFILER = os.getenv('SILKY_PYTHON_PROFILER', 'False').lower() in ('true', '1', 'yes')
SILKY_PYTHON_PROFILER_BINARY = os.getenv('SILKY_PYTHON_PROFILER_BINARY', 'False').lower() in ('true', '1', 'yes')
SILKY_INTERCEPT_PERCENT = int(os.getenv('SILKY_INTERCEPT_PERCENT', '20' if DEBUG else '5'))

# Social auth providers — W001s here are runtime-env issues (no OAuth creds in dev/CI),
# not code bugs. Silence only those.
SILENCED_SYSTEM_CHECKS = ['socialaccount.W001']
