# Generated by Django 6.0.3 on 2026-04-01 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('new_users_today', models.PositiveIntegerField(default=0)),
                ('active_users_today', models.PositiveIntegerField(default=0)),
                ('total_listings', models.PositiveIntegerField(default=0)),
                ('new_listings_today', models.PositiveIntegerField(default=0)),
                ('active_listings', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('orders_today', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_today', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('views_today', models.PositiveIntegerField(default=0)),
                ('total_searches', models.PositiveIntegerField(default=0)),
                ('searches_today', models.PositiveIntegerField(default=0)),
                ('average_trust_score', models.FloatField(default=0.0)),
                ('verified_users', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Platform Metrics',
                'verbose_name_plural': 'Platform Metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_p_date_82cc92_idx')],
            },
        ),
        migrations.CreateModel(
            name='SellerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_listings', models.PositiveIntegerField(default=0)),
                ('active_listings', models.PositiveIntegerField(default=0)),
                ('sold_listings', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_favorites', models.PositiveIntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Stats',
                'verbose_name_plural': 'Seller Stats',
            },
        ),
    ]
