# Generated by Django 6.0.3 on 2026-04-01 11:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('percentage', 'Percentage Only'), ('fixed', 'Fixed Flat Fee'), ('hybrid', 'Percentage + Fixed')], default='percentage', max_length=20)),
                ('percentage_value', models.DecimalField(decimal_places=2, default=5.0, help_text='e.g., 5.00 for 5%', max_digits=5)),
                ('fixed_value', models.DecimalField(decimal_places=2, default=0, help_text='e.g., flat 1,000 TZS fee', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules override lower ones if multiple match.')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('shipping', 'Shipping'), ('pickup', 'Pickup'), ('digital', 'Digital Delivery'), ('local_delivery', 'Local Delivery')], db_index=True, default='shipping', max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(max_length=300)),
                ('address_line2', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Tanzania', max_length=100)),
                ('tracking_number', models.CharField(blank=True, db_index=True, help_text='Carrier tracking number', max_length=100)),
                ('carrier', models.CharField(blank=True, help_text='Shipping carrier (DHL, FedEx, etc.)', max_length=50)),
                ('tracking_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('returned', 'Returned')], db_index=True, default='pending', max_length=20)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('signature_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all order items', max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Shipping/delivery cost', max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, help_text='Platform commission/fee', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount (subtotal + shipping + platform_fee)', max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('shipping_address', models.TextField(blank=True)),
                ('shipping_method', models.CharField(blank=True, help_text='standard, express, pickup, etc.', max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('arrival_location', models.CharField(blank=True, help_text='Exact location where the order arrived (provided by seller)', max_length=255)),
                ('buyer_notes', models.TextField(blank=True, help_text='Notes from buyer')),
                ('seller_notes', models.TextField(blank=True, help_text='Internal notes from seller')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from platform administrators')),
                ('shipment_video', models.FileField(blank=True, null=True, upload_to='shipments/videos/')),
                ('shipment_images_count', models.PositiveIntegerField(default=0, help_text='Number of evidence images uploaded')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, help_text='When the package arrived at its destination', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='order_evidence/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Order Evidence',
                'verbose_name_plural': 'Order Evidence Items',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed (Order Created)'), ('released', 'Released'), ('expired', 'Expired')], db_index=True, default='reserved', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When reservation expires (typically 15-30 minutes)')),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_time', models.DecimalField(decimal_places=2, help_text='Price snapshot when added to cart', max_digits=12)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.cart')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
    ]
