# Generated by Django 6.0.3 on 2026-04-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_orderauditlog_correlation_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderauditlog',
            new_name='commerce_or_order_i_497b63_idx',
            old_name='co_oal_order_created',
        ),
        migrations.RenameIndex(
            model_name='orderauditlog',
            new_name='commerce_or_action_f94585_idx',
            old_name='co_oal_action_created',
        ),
        migrations.RenameIndex(
            model_name='orderauditlog',
            new_name='commerce_or_correla_792a8c_idx',
            old_name='co_oal_corr_created',
        ),
    ]
