# Generated by Django 5.1.14 on 2026-04-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_listingoffer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listingoffer',
            new_name='commerce_li_buyer_i_a91604_idx',
            old_name='commerce_li_buyer_i_idx',
        ),
        migrations.RenameIndex(
            model_name='listingoffer',
            new_name='commerce_li_listing_822602_idx',
            old_name='commerce_li_listing_idx',
        ),
    ]
