# Generated by Django 6.0.3 on 2026-04-01 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insights', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingengagement',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='sellerleadmetrics',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyengagementpattern',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['session_id', 'created_at'], name='insights_ev_session_1d26ab_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'created_at'], name='insights_ev_user_id_46aab3_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'created_at'], name='insights_ev_event_t_653952_idx'),
        ),
        migrations.AddIndex(
            model_name='geographicinsight',
            index=models.Index(fields=['seller', '-date'], name='insights_ge_seller__00bb89_idx'),
        ),
        migrations.AddIndex(
            model_name='geographicinsight',
            index=models.Index(fields=['location_name', '-date'], name='insights_ge_locatio_7c935e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='geographicinsight',
            unique_together={('location_name', 'seller', 'date')},
        ),
        migrations.AddIndex(
            model_name='sellerleadmetrics',
            index=models.Index(fields=['seller', '-date'], name='insights_se_seller__b38f6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerleadmetrics',
            unique_together={('seller', 'date')},
        ),
        migrations.AddIndex(
            model_name='weeklyengagementpattern',
            index=models.Index(fields=['seller', '-week_start_date'], name='insights_we_seller__473ae7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyengagementpattern',
            unique_together={('seller', 'week_start_date', 'day_of_week')},
        ),
    ]
