# Generated by Django 6.0.3 on 2026-04-01 11:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.listing')),
            ],
            options={
                'verbose_name': 'Marketplace Item',
                'verbose_name_plural': 'Marketplace Items',
                'ordering': ['-created_at'],
            },
            bases=('listings.listing',),
        ),
        migrations.CreateModel(
            name='ProductModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('is_safe', models.BooleanField(db_index=True, default=True)),
                ('unsafe_reasons', models.JSONField(blank=True, default=list)),
                ('safe_search_result', models.JSONField(blank=True, default=dict)),
                ('moderated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='marketplace.marketplaceitem')),
            ],
            options={
                'verbose_name': 'Product Moderation Log',
                'verbose_name_plural': 'Product Moderation Logs',
                'ordering': ['-moderated_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(blank=True, help_text='Business/Store name', max_length=200)),
                ('business_type', models.CharField(choices=[('individual', 'Individual Seller'), ('business', 'Business'), ('retailer', 'Retailer'), ('wholesaler', 'Wholesaler')], default='individual', max_length=50)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=50)),
                ('business_phone', models.CharField(blank=True, max_length=20)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_address', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Verified seller badge')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_documents', models.JSONField(blank=True, default=list, help_text='List of uploaded verification document URLs')),
                ('store_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('store_categories', models.JSONField(blank=True, default=list, help_text='What the seller sells; list of category slugs (e.g. electronics, fashion).')),
                ('store_category_other', models.CharField(blank=True, help_text='Details when "other" is selected among store categories.', max_length=200)),
                ('store_category', models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home'), ('food', 'Food'), ('auto_parts', 'Auto parts'), ('books', 'Books'), ('beauty', 'Beauty'), ('sports', 'Sports'), ('other', 'Other')], help_text='Legacy primary category; kept in sync with the first entry in store_categories.', max_length=50)),
                ('store_location', models.CharField(blank=True, max_length=100)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('verification_status', models.CharField(choices=[('incomplete', 'Incomplete'), ('pending_id', 'Pending ID'), ('under_review', 'Under review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='incomplete', max_length=20)),
                ('products_limit', models.PositiveIntegerField(default=50)),
                ('payout_limit', models.DecimalField(decimal_places=2, default=500000.0, help_text='Monthly payout cap in TZS; 0 means unlimited after business upgrade', max_digits=12)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, help_text='Total sales revenue in TZS (denormalized)', max_digits=14)),
                ('completed_orders', models.PositiveIntegerField(default=0, help_text='Count of completed orders (denormalized)')),
                ('is_business_verified', models.BooleanField(db_index=True, default=False, help_text='Verified Business badge after optional business upgrade')),
                ('average_rating', models.FloatField(default=0.0, help_text='Average rating from reviews', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Store visible to buyers when True and identity verified')),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('store_description', models.TextField(blank=True)),
                ('notification_orders', models.BooleanField(default=True)),
                ('notification_messages', models.BooleanField(default=True)),
                ('notification_reviews', models.BooleanField(default=True)),
                ('notification_marketing', models.BooleanField(default=False)),
                ('auto_accept_orders', models.BooleanField(default=False)),
                ('require_phone_confirmation', models.BooleanField(default=True)),
                ('shipping_method', models.CharField(choices=[('standard', 'Standard Shipping'), ('express', 'Express Shipping'), ('pickup', 'Local Pickup')], default='standard', max_length=50)),
                ('return_policy', models.TextField(blank=True, default='7 days return policy for defective items')),
                ('user', models.OneToOneField(help_text='User account associated with this seller profile', on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Profile',
                'verbose_name_plural': 'Seller Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('mpesa', 'M-PESA (Vodacom)'), ('tigo_pesa', 'Tigo Pesa'), ('airtel_money', 'Airtel Money'), ('halopesa', 'HaloPesa'), ('ezypesa', 'EzyPesa'), ('azampesa', 'AzamPesa'), ('bank', 'Bank Transfer'), ('card_visa', 'Visa'), ('card_mastercard', 'Mastercard'), ('card_unionpay', 'UnionPay'), ('till', 'Selcom Till / TanQR')], max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='marketplace.sellerprofile')),
            ],
            options={
                'verbose_name': 'Seller Payment Method',
                'verbose_name_plural': 'Seller Payment Methods',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='stores/banners/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured stores appear in marketplace highlights')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Social media links (facebook, instagram, twitter, etc.)')),
                ('total_listings', models.PositiveIntegerField(default=0)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('total_followers', models.PositiveIntegerField(default=0)),
                ('seller', models.ForeignKey(help_text='Seller who owns this store', on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='marketplace.sellerprofile')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['-is_featured', '-total_sales', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='marketplace.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Follow',
                'verbose_name_plural': 'Store Follows',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_text', models.CharField(blank=True, max_length=255, null=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='catalog.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='marketplace.marketplaceitem')),
                ('value_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_values', to='catalog.attributeoption')),
            ],
            options={
                'verbose_name': 'Product Attribute Value',
                'verbose_name_plural': 'Product Attribute Values',
                'unique_together': {('product', 'attribute')},
            },
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['is_verified', 'is_active'], name='marketplace_is_veri_d7a2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['average_rating', '-completed_orders'], name='marketplace_average_6276a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('store_name__gt', '')), fields=('store_name',), name='uniq_sellerprofile_store_name_when_set'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['seller', 'is_active'], name='marketplace_seller__ffbe16_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_featured', '-total_sales'], name='marketplace_is_feat_3e59f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storefollow',
            unique_together={('user', 'store')},
        ),
    ]
