# Generated by Django 6.0.3 on 2026-04-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_sellerprofile_verification_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sellerprofile',
            new_name='marketplace_verific_41b1cd_idx',
            old_name='market_seller_verif_act_idx',
        ),
    ]
