# Generated by Django 6.0.3 on 2026-04-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rename_market_seller_verif_act_idx_marketplace_verific_41b1cd_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpaymentmethod',
            name='account_number',
            field=models.CharField(max_length=255),
        ),
    ]
