# Generated by Django 5.1.14 on 2026-04-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_sellerpaymentmethod_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_type',
            field=models.CharField(choices=[('product', 'Physical / Digital Product'), ('service', 'Service')], db_index=True, default='product', help_text='Whether the seller offers products or services.', max_length=20),
        ),
    ]
