# Generated by Django 5.1.14 on 2026-04-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_seller_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='store_banner',
            field=models.ImageField(blank=True, help_text="Banner image for the seller's storefront", null=True, upload_to='store_banners/'),
        ),
    ]
