# Generated by Django 6.0.3 on 2026-04-01 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='listings/media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Listing Media',
                'verbose_name_plural': 'Listing Media Items',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, help_text='Price in the specified currency', max_digits=12)),
                ('currency', models.CharField(default='TZS', help_text='ISO 4217 currency code (TZS, USD, etc.)', max_length=3)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('service', 'Service')], db_index=True, default='sale', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('flagged', 'Flagged'), ('sold', 'Sold'), ('rented', 'Rented'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=1, help_text='Available stock quantity (1 for unique items, >1 for products)')),
                ('track_inventory', models.BooleanField(db_index=True, default=False, help_text='Whether to track inventory for this listing')),
                ('low_stock_threshold', models.PositiveIntegerField(default=0, help_text='Alert when stock falls below this threshold')),
                ('allow_backorders', models.BooleanField(default=False, help_text='Allow orders when out of stock')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('region', models.CharField(blank=True, help_text='State/Region', max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('not_applicable', 'N/A')], db_index=True, default='new', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Only published listings are visible to public')),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Category-specific attributes (bedrooms, brand, etc.)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Admin-verified listing')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Promoted listing')),
                ('featured_at', models.DateTimeField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(db_index=True, default=False, help_text='Flagged for review due to suspicious activity')),
                ('flagged_reason', models.TextField(blank=True, help_text='Reason for flagging')),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('price_anomaly_score', models.FloatField(blank=True, help_text='Price anomaly detection score (0-1, higher = more suspicious)', null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category determines which dynamic fields are available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_listings', to='catalog.category')),
                ('owner', models.ForeignKey(blank=True, help_text='User who created this listing. Null if seller is deleted/banned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
