# Generated by Django 6.0.3 on 2026-04-01 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Storefront this listing belongs to. Null if store is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_listings', to='marketplace.store'),
        ),
        migrations.AddField(
            model_name='listinglike',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='listinglike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingmedia',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='listingview',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_history', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='listingview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='listinglike',
            unique_together={('listing', 'user')},
        ),
    ]
