# Generated by Django 6.0.3 on 2026-04-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_browse_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('active', 'Active'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('sold', 'Sold'), ('rented', 'Rented'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
    ]
