# Generated by Django 6.0.3 on 2026-04-01 11:29

import shortlinks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=2000)),
                ('code', models.CharField(default=shortlinks.models.generate_short_code, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
