# Generated by Django 6.0.3 on 2026-04-01 11:29

import core.models.media
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='site/banner/')),
                ('admin_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_contact_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('platform_name', models.CharField(default='SmartDalali', max_length=100)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('min_listing_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_listing_price', models.DecimalField(decimal_places=2, default=100000000.0, max_digits=12)),
                ('enable_escrow', models.BooleanField(default=True)),
                ('auto_approve_listings', models.BooleanField(default=False)),
                ('require_phone_verification', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('enable_push_notifications', models.BooleanField(default=True)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('default_currency', models.CharField(default='TZS', max_length=10)),
                ('default_language', models.CharField(default='en', max_length=10)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g. FontAwesome or Material Icon)', max_length=50)),
                ('vertical', models.CharField(choices=[('property', 'Real Estate'), ('vehicle', 'Vehicles'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['vertical', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=core.models.media.upload_to_marketplace)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('is_main', models.BooleanField(default=False, help_text='Is this the primary cover image?')),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_media', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Media',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_media_content_217c62_idx')],
            },
        ),
    ]
