# Generated by Django 6.0.3 on 2026-04-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_outboxevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='core_outbox_status_99ab3a_idx',
            old_name='core_outbox_status_created_idx',
        ),
    ]
